---
language: ruby
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - 2.2.10
  - jruby-9.2.9.0
  - jruby-9.1.17.0
  - jruby-head
  - ruby-head
  - truffleruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
gemfile:
  - Gemfile
before_script:
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
